version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/r4p8v1i2
  build:
    commands:
      - echo Building Docker image...
      - docker build -t gturyuety .
      - echo Pushing Docker image to ECR...
      - docker tag gturyuety:latest public.ecr.aws/r4p8v1i2/gturyuety:latest
      - docker push public.ecr.aws/r4p8v1i2/gturyuety:latest
  post_build:
    commands:
      - echo Generating artifact...
artifacts:
  files:
    - path/to/artifact
