version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 143998996404.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t myapplogin .
      - echo Pushing Docker image to ECR...
      - docker tag myapplogin:latest 143998996404.dkr.ecr.us-east-2.amazonaws.com/myapplogin:loginapp
      - docker push 143998996404.dkr.ecr.us-east-2.amazonaws.com/myapplogin:loginapp
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 143998996404.dkr.ecr.us-east-2.amazonaws.com/myapplogin:loginapp
      - echo Writing image definitions file...
      - printf '[{"name":"loginapp-file","imageUri":"143998996404.dkr.ecr.us-east-2.amazonaws.com/myapplogin:loginapp"}]' > imagedefinitions.json
artifacts:
 files:
 - imagedefinitions.json
