version: "3"
services:
  app:
    image: login-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/app/src
      - ./public:/app/public
  nginx:
    image: nginx:1.21.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  